import sequelize from '../lib/sequelize.js';
import { DataTypes } from 'sequelize';

const PersonalDetails = sequelize.define('PersonalDetails', {
  id: {
    type: DataTypes.INTEGER,
    autoIncrement: true,
    primaryKey: true,
  },
  subject: { type: DataTypes.STRING(10), allowNull: true },
  roll: { type: DataTypes.STRING(10), allowNull: true },
  name_English: { type: DataTypes.TEXT, allowNull: true  },
  name_Bangla: { type: DataTypes.TEXT, allowNull: true },
  birth: { type: DataTypes.STRING(10), allowNull: true }, // Assuming birth date is in YYYY-MM-DD format
  religion: { type: DataTypes.STRING(100), allowNull: true },
  mobile: { type: DataTypes.STRING(15), allowNull: true }, // Adjust size as needed
  married: { type: DataTypes.STRING(10), allowNull: true },
  fathers_Name_English: { type: DataTypes.STRING(100), allowNull: true },
  fathers_Name_Bangla: { type: DataTypes.STRING(100), allowNull: true },
  fathers_Nid: { type: DataTypes.STRING(20), allowNull: true },
  fathers_Mobile: { type: DataTypes.STRING(15), allowNull: true },
  mothers_Name_English: { type: DataTypes.STRING(100), allowNull: true },
  mothers_Name_Bangla: { type: DataTypes.STRING(100), allowNull: true },
  mothers_Nid: { type: DataTypes.STRING(20), allowNull: true },
  mothers_Mobile: { type: DataTypes.STRING(15), allowNull: true },
  address_Permanent: { type: DataTypes.TEXT, allowNull: true },
  district_Permanent: { type: DataTypes.STRING(100), allowNull: true },
  zip_Permanent: { type: DataTypes.STRING(10), allowNull: true },
  address_Current: { type: DataTypes.TEXT, allowNull: true },
  district_Current: { type: DataTypes.STRING(100), allowNull: true },
  zip_Current: { type: DataTypes.STRING(10), allowNull: true },
  guardians_Name: { type: DataTypes.STRING(100), allowNull: true },
  guardians_Monthly_Income: { type: DataTypes.STRING(20), allowNull: true },
  guardians_Occupation: { type: DataTypes.STRING(100), allowNull: true },
  guardians_Mobile_Number: { type: DataTypes.STRING(15), allowNull: true },
  subjectsA: { type: DataTypes.TEXT, allowNull: true },
  subjectsB: { type: DataTypes.TEXT, allowNull: true },
  fourthSubject: { type: DataTypes.TEXT, allowNull: true },
  ssc_Section: { type: DataTypes.STRING(10), allowNull: true },
  ssc_Board: { type: DataTypes.STRING(100), allowNull: true },
  ssc_Roll: { type: DataTypes.STRING(20), allowNull: true },
  ssc_Registration: { type: DataTypes.STRING(20), allowNull: true },
  ssc_Year_Span: { type: DataTypes.STRING(20), allowNull: true },
  sss_Year: { type: DataTypes.STRING(20), allowNull: true },
  ssc_GPA: { type: DataTypes.STRING(5), allowNull: false },
  ssc_Institution_Name: { type: DataTypes.STRING(100), allowNull: true },
  ssc_Institution_Address: { type: DataTypes.TEXT, allowNull: true },
  ssc_Institution_Zip: { type: DataTypes.STRING(10), allowNull: true },
  ssc_Institution_District: { type: DataTypes.STRING(100), allowNull: true },
  ssc_Institution_Village: { type: DataTypes.STRING(100), allowNull: true },
  subject_List: { type: DataTypes.TEXT, allowNull: true },
  extracurriculars: { type: DataTypes.TEXT, allowNull: true },
  hobbies: { type: DataTypes.TEXT, allowNull: true },
  social_Service: { type: DataTypes.TEXT, allowNull: true },
  ssc_Transcript: { type: DataTypes.STRING(100), allowNull: true },
  ssc_Certificate: { type: DataTypes.STRING(100), allowNull: true },
  ssc_Registration: { type: DataTypes.STRING(20), allowNull: true },
  ssc_Admit: { type: DataTypes.STRING(100), allowNull: true },
  image: { type: DataTypes.STRING(255), allowNull: true },
  birth_Certificate: { type: DataTypes.STRING(100), allowNull: true },
  fathers_Nid_Card: { type: DataTypes.STRING(100), allowNull: true },
  mothers_Nid_Card: { type: DataTypes.STRING(100), allowNull: true },
});

export default PersonalDetails;
