import mongoose from 'mongoose';

const PersonalDetailsSchema = new mongoose.Schema({

  subject: { type: String, required: false },
  roll: { type: String, required: false },
  name_English: { type: String, required: false },
  name_Bangla: { type: String, required: false },
  birth: { type: String, required: false }, // Assuming birth date is in YYYY-MM-DD format
  birthRegNo: { type: String, required: false },
  religion: { type: String, required: false },
  mobile: { type: String, required: false }, // Adjust size as needed
  married: { type: String, required: false },
  fathers_Name_English: { type: String, required: false },
  fathers_Name_Bangla: { type: String, required: false },
  fathers_Nid: { type: String, required: false },
  fathers_Mobile: { type: String, required: false },
  mothers_Name_English: { type: String, required: false },
  mothers_Name_Bangla: { type: String, required: false },
  mothers_Nid: { type: String, required: false },
  mothers_Mobile: { type: String, required: false },
  address_Permanent: { type: String, required: false },
  district_Permanent: { type: String, required: false },
  zip_Permanent: { type: String, required: false },
  thana_Permanent: { type: String, required: false },
  address_Current: { type: String, required: false },
  district_Current: { type: String, required: false },
  zip_Current: { type: String, required: false },
  thana_Current: { type: String, required: false },
  guardians_Name: { type: String, required: false },
  guardians_Monthly_Income: { type: String, required: false },
  guardians_Occupation: { type: String, required: false },
  guardians_Mobile_Number: { type: String, required: false },
  subjectsA: { type: String, required: false },
  subjectsB: { type: String, required: false },
  fourthSubject: { type: String, required: false },
  ssc_Section: { type: String, required: false },
  ssc_Board: { type: String, required: false },
  ssc_Roll: { type: String, required: false },

  ssc_Year_Span: { type: String, required: false },
  sss_Year: { type: String, required: false },
  ssc_GPA: { type: String, required: true },
  ssc_Institution_Name: { type: String, required: false },
  ssc_Institution_Address: { type: String, required: false },
  ssc_Institution_Zip: { type: String, required: false },
  ssc_Institution_District: { type: String, required: false },
  ssc_Institution_Village: { type: String, required: false },
  ssc_Institution_Thana: { type: String, required: false },
  subject_List: { type: String, required: false },
  extracurriculars: { type: String, required: false },
  hobbies: { type: String, required: false },
  social_Service: { type: String, required: false },
  ssc_Transcript: { type: String, required: false },
  ssc_Certificate: { type: String, required: false },
  ssc_Registration: { type: String, required: false },
  ssc_Admit: { type: String, required: false },
  image: { type: String, required: false },
  birth_Certificate: { type: String, required: false },
  fathers_Nid_Card: { type: String, required: false },
  mothers_Nid_Card: { type: String, required: false },
});

// Export the model
export default mongoose.models.PersonalDetails || mongoose.model('PersonalDetails', PersonalDetailsSchema);
